# Generated by Django 4.1.3 on 2022-11-07 12:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. 20 characters or fewer. Digits and + only.', max_length=20, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
