# Generated by Django 4.1.3 on 2022-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=1, max_length=6, verbose_name='phone verification key'),
            preserve_default=False,
        ),
    ]
