# Generated by Django 4.1.3 on 2022-11-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='phone verification key'),
        ),
    ]
