# Generated by Django 4.1.3 on 2022-11-05 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sub_categories', models.ManyToManyField(blank=True, related_name='parent_category', to='product.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 11, 5, 12, 7, 30, 316708, tzinfo=datetime.timezone.utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
