# Generated by Django 4.1.3 on 2022-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='parent_category', to='product.category'),
        ),
    ]
