# Generated by Django 4.1.3 on 2022-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
