# Generated by Django 4.1.3 on 2022-11-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_address_default_cartitem_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('courier', 'courier'), ('pickup', 'pickup')], default='courier', max_length=15)),
                ('date', models.DateField()),
                ('time', models.DurationField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('stripe', 'stripe'), ('cash', 'cash')], default='cash', max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
            ],
        ),
    ]
