# Generated by Django 4.1.3 on 2022-11-08 15:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 8, 15, 58, 51, 282172, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
