# Generated by Django 4.1.3 on 2022-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_favouriteproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artikul_number',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
