# Generated by Django 4.1.3 on 2022-11-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_artikul_number_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artikul_number',
            field=models.CharField(max_length=20),
        ),
    ]
